// Centralized service for fetching initiatives data
// This can be easily swapped with Axios/Fetch calls to a real API in the future.

export const fetchCampaigns = async () => {
  // Simulate API delay
  await new Promise((resolve) => setTimeout(resolve, 500));

  return [
    {
      id: "camp-1",
      img: "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?auto=format&fit=crop&w=600&q=80",
      title: "Support Urban Education Initiatives",
      tag: "Education",
      category: "Education",
      location: "Mumbai, India",
      raised: 45000,
      goal: 100000,
      donors: 156,
      isVerified: true,
      isTaxExempt: true,
      organizer: "Education First",
      desc: "Providing essential school supplies and tutoring for children in underserved urban communities.",
      sdgs: [4, 10],
    },
    {
      id: "camp-2",
      img: "https://images.unsplash.com/photo-1516939884455-1445c8652f83?auto=format&fit=crop&w=800&q=80",
      title: "Clean Water Project for Rural Areas",
      tag: "Environment",
      category: "Environment",
      location: "Rajasthan, India",
      raised: 75000,
      goal: 150000,
      donors: 89,
      isVerified: true,
      isTaxExempt: false,
      organizer: "NatureCare",
      desc: "Building sustainable water wells and filtration systems for remote villages.",
      sdgs: [6, 13],
    },
    {
      id: "camp-3",
      img: "https://images.unsplash.com/photo-1469571486292-0ba58a3f068b?auto=format&fit=crop&w=600&q=80",
      title: "Volunteer Groups Making Real Impact",
      tag: "Community",
      category: "Community",
      location: "Pune, India",
      raised: 232609,
      goal: 400000,
      donors: 112,
      isVerified: false,
      isTaxExempt: true,
      organizer: "Community Builders",
      desc: "Join our campaign to bring joy to children, women and the elderly across the globe.",
      sdgs: [11, 17],
    },
    {
      id: "camp-4",
      img: "https://images.unsplash.com/photo-1594708767771-a7502209ff51?auto=format&fit=crop&w=600&q=80",
      title: "Solar Energy for Tribal Schools",
      tag: "Environment",
      category: "Environment",
      location: "Odisha, India",
      raised: 15000,
      goal: 60000,
      donors: 45,
      isVerified: true,
      isTaxExempt: true,
      organizer: "Green Power Foundation",
      desc: "Installing solar panels in schools to provide consistent electricity for digital learning.",
      sdgs: [7, 4],
    },
    {
      id: "camp-5",
      img: "https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&w=800&q=80",
      title: "Nutrition Program for Toddlers",
      tag: "Healthcare",
      category: "Healthcare",
      location: "Bihar, India",
      raised: 30000,
      goal: 80000,
      donors: 210,
      isVerified: true,
      isTaxExempt: false,
      organizer: "Healthy Start NGO",
      desc: "Fighting malnutrition by providing fortified meals to children under the age of five.",
      sdgs: [2, 3],
    },
    {
      id: "camp-6",
      img: "https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=600&q=80",
      title: "Skill Development for Rural Youth",
      tag: "Education",
      category: "Education",
      location: "Uttar Pradesh, India",
      raised: 120000,
      goal: 250000,
      donors: 340,
      isVerified: false,
      isTaxExempt: true,
      organizer: "Uday Foundation",
      desc: "Providing vocational training in electronics and stitching to empower young adults.",
      sdgs: [8, 4],
    },
  ];
};

export const fetchEvents = async () => {
  await new Promise((resolve) => setTimeout(resolve, 500));

  return [
    {
      id: "event-1",
      img: "https://images.unsplash.com/photo-1511632765486-a01980e01a18?auto=format&fit=crop&w=600&q=80",
      date: "15 Sept 2024",
      title: "Global Charity Run for Health",
      organizer: "Health Foundation",
      time: "07:00 AM",
      location: "Mumbai, India",
      desc: "Join us for our annual charity run to raise funds for critical healthcare services.",
      isVerified: true,
      isTaxExempt: true,
      category: "Healthcare",
      eventType: "physical",
      status: "active",
      raised: 12000,
      goal: 50000,
    },
    {
      id: "event-2",
      img: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=600&q=80",
      date: "20 Oct 2024",
      title: "Youth Empowerment Workshop",
      organizer: "Youth Link",
      time: "10:00 AM",
      location: "Online",
      desc: "A virtual workshop focused on leadership skills and career development for teenagers.",
      isVerified: true,
      isTaxExempt: false,
      category: "Education",
      eventType: "virtual",
      status: "active",
      raised: 5000,
      goal: 20000,
    },
    {
      id: "event-3",
      img: "https://images.unsplash.com/photo-1531206715517-5c0ba140b2b8?auto=format&fit=crop&w=600&q=80",
      date: "12 Nov 2024",
      title: "Eco-Awareness Seminar",
      organizer: "Green Earth",
      time: "02:00 PM",
      location: "Bangalore, India",
      desc: "A seminar on sustainable living and reducing plastic footprint in urban cities.",
      isVerified: true,
      isTaxExempt: true,
      category: "Environment",
      eventType: "hybrid",
      status: "active",
      raised: 2500,
      goal: 10000,
    },
    {
      id: "event-4",
      img: "https://images.unsplash.com/photo-1477414348463-c0eb7f1359b6?auto=format&fit=crop&w=800&q=80",
      date: "05 Dec 2024",
      title: "Winter Relief Drive 2024",
      organizer: "Social Care NGO",
      time: "09:00 AM",
      location: "Delhi, India",
      desc: "Distributing blankets and warm clothes to the homeless across North India.",
      isVerified: false,
      isTaxExempt: true,
      category: "Community",
      eventType: "physical",
      status: "active",
      raised: 15000,
      goal: 30000,
    },
    {
      id: "event-5",
      img: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=800&q=80",
      date: "18 Jan 2025",
      title: "Future of Healthcare Tech",
      organizer: "MedTech Innovations",
      time: "04:00 PM",
      location: "San Francisco, USA",
      desc: "Exploring how AI and robotics are transforming global medical access.",
      isVerified: true,
      isTaxExempt: false,
      category: "Healthcare",
      eventType: "virtual",
      status: "active",
      raised: 8000,
      goal: 15000,
    },
  ];
};

export const fetchFundraisers = async () => {
  await new Promise((resolve) => setTimeout(resolve, 500));

  return [
    {
      id: "fund-1",
      img: "https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=600&q=80",
      title: "Classroom Revitalization Project",
      organizer: "Sarah Johnson",
      name: "Sarah Johnson",
      campaignName: "Education First NGO",
      location: "New York, USA",
      category: "Education",
      desc: "Helping local schools upgrade their technology and learning environments.",
      raised: 8500,
      goal: 15000,
      donors: 42,
      isVerified: true,
      isTaxExempt: true,
      type: "Individual",
    },
    {
      id: "fund-2",
      img: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80",
      title: "Emergency Food Relief Fund",
      organizer: "Alex Williams",
      name: "Alex Williams",
      campaignName: "NatureCare Foundation",
      location: "London, UK",
      category: "Healthcare",
      desc: "Providing meals and nutritional support to families in crisis.",
      raised: 45000,
      goal: 50000,
      donors: 128,
      isVerified: true,
      isTaxExempt: true,
      type: "NGO",
    },
    {
      id: "fund-3",
      img: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80",
      title: "Support for Homeless Shelter",
      organizer: "David Miller",
      name: "David Miller",
      campaignName: "City Care",
      location: "Chicago, USA",
      category: "Community",
      desc: "Upgrading our kitchen to serve over 500 meals daily to the homeless.",
      raised: 2200,
      goal: 10000,
      donors: 35,
      isVerified: true,
      isTaxExempt: false,
      type: "Individual",
    },
    {
      id: "fund-4",
      img: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=80",
      title: "Children's Heart Surgery Fund",
      organizer: "Dr. Robert Chen",
      name: "Dr. Robert Chen",
      campaignName: "HeartBeat India",
      location: "Chennai, India",
      category: "Healthcare",
      desc: "Funding critical surgeries for children from low-income families.",
      raised: 120000,
      goal: 300000,
      donors: 520,
      isVerified: true,
      isTaxExempt: true,
      type: "Campaign",
    },
    {
      id: "fund-5",
      img: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=600&q=80",
      title: "Scholarship for Girls in STEM",
      organizer: "Anita Desai",
      name: "Anita Desai",
      campaignName: "Women in Tech",
      location: "Pune, India",
      category: "Education",
      desc: "Creating 50 full-ride scholarships for girls pursuing engineering degrees.",
      raised: 60000,
      goal: 200000,
      donors: 180,
      isVerified: false,
      isTaxExempt: true,
      type: "Campaign",
    },
  ];
};
